name: human_alignment
channels:
 - defaults
 - conda-forge
 - pytorch
dependencies:
 - python=3.9
 - numpy=1.22.*
 - pandas=1.4.*
 - matplotlib=3.5.*
 - seaborn=0.11.* 
 - tqdm=4.64.*
 - pytorch=1.11.*
 - torchvision=0.12.*
 - Pillow=9.1.* 
 - pip
 - pip:
   - thingsvision==1.6.0 
   - functorch==0.1.*
   - pytorch_lightning==1.7.*
   - tueplots 
   - ml_collections 
   - pyflakes
   - isort
   - black
